AllCops:
  TargetRailsVersion: 4.0

  Include:
  - "**/*.rake"
  - "**/Gemfile"
  - "**/Rakefile"
  Exclude:
  - "vendor/**/*"
  - "db/**/*"
  - "client/**/*"

Rails/UnknownEnv:
  Environments:
    - development
    - production
    - test
    - staging

Lint/EndAlignment:
  EnforcedStyleAlignWith: variable

Metrics/LineLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Rails:
  Enabled: true

# https://github.com/bbatsov/rubocop/issues/3629
Rails/HttpPositionalArguments:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Rails/FilePath:
  Enabled: false

Metrics/AbcSize:
  Max: 20

Metrics/MethodLength:
  Max: 20

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Style/GuardClause:
  Enabled: false

Layout/IndentArray:
  EnforcedStyle: consistent

Layout/IndentHash:
  EnforcedStyle: consistent

Layout/MultilineMethodCallBraceLayout:
  EnforcedStyle: new_line

Style/MutableConstant:
  Enabled: false

Style/Send:
  Enabled: true

Style/StringLiterals:
  Enabled: false
