AllCops:
  Include:
  - "**/*.rake"
  - "**/Gemfile"
  - "**/Rakefile"
  Exclude:
  - "vendor/**/*"
  - "db/**/*"
  - "client/**/*"
  RunRailsCops: true

GuardClause:
  Enabled: false

Documentation:
  Enabled: false

StringLiterals:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining

# https://github.com/bbatsov/rubocop/issues/1758
Style/ClosingParenthesisIndentation:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Style/Send:
  Enabled: true

Lint/EndAlignment:
  AlignWith: variable
