AllCops:
  Include:
  - "**/*.rake"
  - "**/Gemfile"
  - "**/Rakefile"
  Exclude:
  - "vendor/**/*"
  - "db/**/*"
  - "client/**/*"
  RunRailsCops: true

GuardClause:
  Enabled: false

Documentation:
  Enabled: false

StringLiterals:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Lint/EndAlignment:
  AlignWith: variable
