AllCops:
  Include:
  - "**/*.rake"
  - "**/Gemfile"
  - "**/Rakefile"
  Exclude:
  - "vendor/**/*"
  - "db/**/*"
  - "client/**/*"
  TargetRubyVersion: 2.3

Lint/EndAlignment:
  AlignWith: variable

Metrics/LineLength:
  Enabled: false

Rails:
  Enabled: true

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining

# https://github.com/bbatsov/rubocop/issues/1758
Style/ClosingParenthesisIndentation:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IndentArray:
  EnforcedStyle: consistent

Style/IndentHash:
  EnforcedStyle: consistent

Style/MutableConstant:
  Enabled: false

Style/Send:
  Enabled: true

Style/StringLiterals:
  Enabled: false
