exclude:
  - 'vendor/assets/stylesheets/**'
  - 'client/bower_components/**/*'
  - 'client/dist/**/*'
  - 'client/node_modules/**/*'
  - 'client/tmp/**/*'
  - 'client/vendor/**/*'

linters:
  SelectorFormat:
    enabled: true
    convention: hyphenated_BEM

  QualifyingElement:
    allow_element_with_attribute: true
