before_install:
  - "echo '--colour' > ~/.rspec"
  - "echo 'gem: --no-document' > ~/.gemrc"
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - bundle config --local path .bundle
  - bundle config --local without development
  - nvm install 0.12
  - nvm use 0.12
  - bin/setup
branches:
  only:
    - master
cache:
  directories:
    - .bundle
    - client/node_modules
    - client/bower_components
language:
  - ruby
notifications:
  email: false
addons:
  postgresql: "9.3"
services:
  - redis-server
sudo: false
