development: &default
  adapter: postgresql
  database: omnibus_development
  encoding: utf8
  host: localhost
  min_messages: warning
  pool: <%= ENV.fetch("DB_POOL", 2) %>
  reaping_frequency: <%= ENV.fetch("DB_REAPING_FREQUENCY", 10) %>
  timeout: 5000

test:
  <<: *default
  database: omnibus_test

production: &deploy
  encoding: utf8
  min_messages: warning
  pool: <%= [ENV.fetch("MAX_THREADS", 2), ENV.fetch("DB_POOL", 2)].max %>
  timeout: 5000
  url: <%= ENV.fetch("DATABASE_URL", "") %>

staging: *deploy
