development: &default
  adapter: postgresql
  database: omnibus_development
  encoding: utf8
  host: localhost
  min_messages: warning
  pool: <%= Integer(ENV.fetch("DB_POOL", 2)) %>
  reaping_frequency: <%= Integer(ENV.fetch("DB_REAPING_FREQUENCY", 10)) %>
  timeout: 5000

test:
  <<: *default
  database: omnibus_test

production: &deploy
  encoding: utf8
  min_messages: warning
  pool: <%= [Integer(ENV.fetch("MAX_THREADS", 2)), Integer(ENV.fetch("DB_POOL", 2))].max %>
  timeout: 5000
  url: <%= ENV.fetch("DATABASE_URL", "") %>

staging: *deploy
