common: &default_settings
  app_name: "Omnibus (<%= Rails.env.capitalize %>)"
  license_key: "<%= ENV['NEW_RELIC_LICENSE_KEY'] %>"
  monitor_mode: true

development:
  <<: *default_settings
  monitor_mode: false

test:
  <<: *default_settings
  monitor_mode: false

staging:
  <<: *default_settings

production:
  <<: *default_settings
